services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: afiliado-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=afiliado_db
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: afiliado-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: afiliado_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
